-- #
-- # TABLE STRUCTURE FOR: Article
-- #
--
-- DROP TABLE IF EXISTS `Article`;

-- CREATE TABLE `Article` (
--   `id` int(11) NOT NULL AUTO_INCREMENT,
--   `title` varchar(60) COLLATE utf8mb4_unicode_ci NOT NULL,
--   `text` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
--   `publish_date` date NOT NULL,
--   `updated_date` date NOT NULL,
--   `author` int(11) DEFAULT NULL,
--   PRIMARY KEY (`id`)
-- ) ENGINE=InnoDB AUTO_INCREMENT=101 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO `mainapp_article` (`id`, `title`, `text`, `publish_date`, `updated_date`, `author`,`category`) VALUES (1, 'Magni qui ea ut voluptates.', 'Ratione veniam est et libero enim. Amet exercitationem illo vel. Harum molestiae minima et dolore odit similique temporibus.', '1984-07-20', '1986-01-03', 1, 1);
INSERT INTO `mainapp_article` (`id`, `title`, `text`, `publish_date`, `updated_date`, `author`,`category`) VALUES (2, 'Et eos tempore totam rerum ut accusantium non.', 'Ducimus quidem aperiam et reiciendis natus sit praesentium necessitatibus. Omnis aut et non error dolorem est. Voluptatem ullam fuga non.', '1972-08-12', '1973-04-18', 1, 1);
INSERT INTO `mainapp_article` (`id`, `title`, `text`, `publish_date`, `updated_date`, `author`,`category`) VALUES (3, 'Sit qui voluptas voluptas facere voluptatem quo.', 'Ipsa est harum porro sint corporis. Voluptas laboriosam assumenda dicta quae dolorem voluptas alias. Eum maiores voluptate voluptas quis eos saepe ea.', '2000-09-05', '2015-11-18', 1, 1);
INSERT INTO `mainapp_article` (`id`, `title`, `text`, `publish_date`, `updated_date`, `author`,`category`) VALUES (4, 'Est quidem quo recusandae voluptates quas est occaecati recu', 'Voluptatem aut cupiditate corporis voluptatibus voluptas eos. Eaque tempora aliquam consectetur doloribus.', '1986-10-02', '2008-02-20', 3, 1);
INSERT INTO `mainapp_article` (`id`, `title`, `text`, `publish_date`, `updated_date`, `author`,`category`) VALUES (5, 'Ex adipisci a temporibus.', 'Quo itaque et velit reprehenderit. Ab similique vel illum dolores quia autem. Vel pariatur consequatur et velit.', '2017-02-05', '2005-10-05', 7, 1);
INSERT INTO `mainapp_article` (`id`, `title`, `text`, `publish_date`, `updated_date`, `author`,`category`) VALUES (6, 'Dignissimos dolore corporis dolor minus dignissimos suscipit', 'Quis voluptas amet voluptatem laborum velit. Tempora minus nostrum quisquam fuga eligendi enim. Sapiente velit mollitia at expedita.', '1996-12-31', '2011-05-22', 9, 1);
INSERT INTO `mainapp_article` (`id`, `title`, `text`, `publish_date`, `updated_date`, `author`,`category`) VALUES (7, 'Nesciunt sint eum vel nihil veniam distinctio in.', 'Aut tenetur dignissimos blanditiis odio reiciendis. Cum reiciendis rerum officiis eveniet sunt. Nemo voluptatem voluptatibus doloribus doloribus explicabo non impedit.', '1995-05-15', '1989-12-11', 2, 1);
INSERT INTO `mainapp_article` (`id`, `title`, `text`, `publish_date`, `updated_date`, `author`,`category`) VALUES (8, 'Dolor labore velit animi sunt.', 'Nostrum quasi omnis nostrum laborum maxime. Beatae aliquam aliquid natus consequatur ullam. Nam odio quos illo et atque.', '1994-12-27', '1993-06-18', 1, 1);
INSERT INTO `mainapp_article` (`id`, `title`, `text`, `publish_date`, `updated_date`, `author`,`category`) VALUES (9, 'Cumque odio totam natus consectetur.', 'Eveniet temporibus occaecati dolorum illum quasi eos in. Qui molestias nihil deserunt ipsum id et ipsa unde. Perferendis sit dolor et corrupti libero. Sunt dolor labore aut odit maiores.', '2018-10-28', '1984-01-07', 2, 1);
INSERT INTO `mainapp_article` (`id`, `title`, `text`, `publish_date`, `updated_date`, `author`,`category`) VALUES (10, 'Voluptatum voluptatibus suscipit magni incidunt neque earum ', 'Nemo est fugiat minus iste. Commodi velit sint et qui cupiditate et. Ex quibusdam ut autem aliquid repudiandae nam expedita.', '1976-09-28', '1986-12-26', 2, 1);
INSERT INTO `mainapp_article` (`id`, `title`, `text`, `publish_date`, `updated_date`, `author`,`category`) VALUES (11, 'Dolor facere dolorem vel perspiciatis quae animi.', 'Iusto nam dolores natus aut debitis eum. Aut eveniet repellat tempora ut qui. Voluptatum exercitationem occaecati adipisci non sint. Totam error porro nesciunt non.', '1970-02-06', '2002-02-01', 5, 1);
INSERT INTO `mainapp_article` (`id`, `title`, `text`, `publish_date`, `updated_date`, `author`,`category`) VALUES (12, 'Et nemo magnam non consectetur similique alias.', 'Non quis at et sit accusantium cupiditate expedita. Maiores aut et aliquid placeat pariatur cum. Beatae ut autem voluptatibus quod. Blanditiis suscipit mollitia autem incidunt ipsa.', '1982-02-08', '1986-05-06', 7, 1);
INSERT INTO `mainapp_article` (`id`, `title`, `text`, `publish_date`, `updated_date`, `author`,`category`) VALUES (13, 'Provident et sint iusto sit aut.', 'Omnis rerum itaque non aut repudiandae nostrum sint voluptatem. Et et et repudiandae vel. Est asperiores in repudiandae ut et.', '2017-06-21', '1995-05-27', 2, 1);
INSERT INTO `mainapp_article` (`id`, `title`, `text`, `publish_date`, `updated_date`, `author`,`category`) VALUES (14, 'Accusamus animi occaecati nulla unde consectetur error et.', 'Aliquid earum sed et ipsa rerum ex nulla. Id voluptas consequuntur sunt saepe modi ut odio. Est debitis a ut recusandae molestiae quidem.', '1978-08-25', '2017-03-13', 2, 1);
INSERT INTO `mainapp_article` (`id`, `title`, `text`, `publish_date`, `updated_date`, `author`,`category`) VALUES (15, 'Ut assumenda voluptas odio ut.', 'Odio dolores inventore aspernatur totam fuga facere et. Cumque sapiente dolor deleniti accusantium cumque. Veritatis facilis eum illo. Ut ipsum quas et saepe a nihil pariatur.', '1980-02-18', '1994-06-16', 3, 1);
INSERT INTO `mainapp_article` (`id`, `title`, `text`, `publish_date`, `updated_date`, `author`,`category`) VALUES (16, 'Nam non et dolorem optio repellendus dolores accusantium.', 'Est accusantium quia nemo non natus accusamus. Impedit sit sed nihil consectetur placeat. Consectetur veniam quam sed qui voluptatum.', '1989-09-13', '1993-02-04', 4, 1);
INSERT INTO `mainapp_article` (`id`, `title`, `text`, `publish_date`, `updated_date`, `author`,`category`) VALUES (17, 'Velit et odit sint quisquam.', 'Tempora animi consequuntur reprehenderit repellendus consectetur ipsam. Maiores fugit facilis dolorem repellendus.', '2002-04-07', '1986-08-20', 4, 1);
INSERT INTO `mainapp_article` (`id`, `title`, `text`, `publish_date`, `updated_date`, `author`,`category`) VALUES (18, 'Minus impedit exercitationem explicabo aut.', 'Nihil et nesciunt voluptatem et iusto a expedita. Ipsam asperiores fugiat aut accusantium inventore. Quibusdam in et rerum officia tempora aliquid.', '2008-07-02', '1992-08-28', 1, 1);
INSERT INTO `mainapp_article` (`id`, `title`, `text`, `publish_date`, `updated_date`, `author`,`category`) VALUES (19, 'Nihil adipisci reiciendis consequatur.', 'Sint itaque accusamus cumque mollitia. Dolore recusandae numquam eveniet qui vero recusandae provident. Temporibus eos ea tempore ut labore. Quod doloribus possimus ad dolores.', '1976-11-16', '1986-02-28', 2, 1);
INSERT INTO `mainapp_article` (`id`, `title`, `text`, `publish_date`, `updated_date`, `author`,`category`) VALUES (20, 'Magni officia voluptas recusandae eaque expedita.', 'Nisi aut consequatur voluptatem at ab fugit. Nam minus provident nisi cupiditate quis blanditiis non. Cumque eaque consequuntur aspernatur et. In sit ut excepturi dolorem omnis officia.', '1998-09-24', '2012-04-07', 9, 1);
INSERT INTO `mainapp_article` (`id`, `title`, `text`, `publish_date`, `updated_date`, `author`,`category`) VALUES (21, 'Praesentium error sed expedita.', 'Voluptas quis sint atque vero enim iure voluptatum repellendus. Amet laudantium accusantium neque est sunt libero consequuntur.', '1971-10-24', '1999-06-09', 5, 1);
INSERT INTO `mainapp_article` (`id`, `title`, `text`, `publish_date`, `updated_date`, `author`,`category`) VALUES (22, 'Eligendi iure ullam eos dolor est.', 'Dolore provident a ad. Qui nulla nobis rem magnam sit et. Ducimus eum asperiores voluptatem dolorem maxime nam magnam id. Blanditiis quia dolore qui ut accusantium doloribus.', '1984-07-25', '1999-02-26', 7, 1);
INSERT INTO `mainapp_article` (`id`, `title`, `text`, `publish_date`, `updated_date`, `author`,`category`) VALUES (23, 'Voluptatum ut dicta qui explicabo commodi.', 'Velit sapiente natus non inventore recusandae. Dolores officia nesciunt sit et expedita. Non nesciunt et id a corrupti autem.', '1987-10-16', '1992-03-17', 7, 1);
INSERT INTO `mainapp_article` (`id`, `title`, `text`, `publish_date`, `updated_date`, `author`,`category`) VALUES (24, 'Magnam sed et aperiam voluptas nemo molestias.', 'Ut qui et expedita nihil perferendis sit excepturi. Reprehenderit magnam sit aut qui qui omnis. Optio ab animi mollitia eligendi delectus et eos.', '1999-03-31', '2009-07-23', 7, 1);
INSERT INTO `mainapp_article` (`id`, `title`, `text`, `publish_date`, `updated_date`, `author`,`category`) VALUES (25, 'In fugit totam aperiam.', 'Est ea soluta voluptas omnis rerum. Qui cupiditate quam aut autem. Nemo ea quia sit molestiae quia inventore et.', '1988-04-18', '1991-07-04', 9, 1);
INSERT INTO `mainapp_article` (`id`, `title`, `text`, `publish_date`, `updated_date`, `author`,`category`) VALUES (26, 'Iste libero facilis velit asperiores dolorum nostrum ullam e', 'Illum tempore autem autem veritatis quas aperiam nesciunt. Nisi possimus illum non. Soluta et harum veniam assumenda. Cumque odio doloremque omnis cupiditate nihil voluptatem nulla et.', '2009-06-19', '1986-03-27', 0, 1);
INSERT INTO `mainapp_article` (`id`, `title`, `text`, `publish_date`, `updated_date`, `author`,`category`) VALUES (27, 'Optio voluptatum ex sit fugit.', 'Et vitae molestiae quas veniam culpa et eos. Doloribus rem dolore tempora asperiores. Consequuntur ea provident sunt consequatur.', '2006-07-25', '1998-01-19', 3, 1);
INSERT INTO `mainapp_article` (`id`, `title`, `text`, `publish_date`, `updated_date`, `author`,`category`) VALUES (28, 'Voluptatem magnam omnis excepturi sequi ut.', 'Soluta nihil porro dolores quisquam. Dolores repellat facere eum autem dignissimos porro id. Et beatae est et magnam quae.', '1998-11-05', '1989-08-01', 4, 1);
INSERT INTO `mainapp_article` (`id`, `title`, `text`, `publish_date`, `updated_date`, `author`,`category`) VALUES (29, 'Rerum blanditiis tenetur hic modi cupiditate.', 'Voluptatum esse nemo eum eligendi laborum reiciendis. Ipsum ut illum recusandae commodi est voluptatum totam rem. Consectetur tempore numquam eum natus.', '1998-11-04', '2013-10-09', 1, 1);
INSERT INTO `mainapp_article` (`id`, `title`, `text`, `publish_date`, `updated_date`, `author`,`category`) VALUES (30, 'Amet illo porro quasi consectetur voluptates.', 'Consequatur atque eius dignissimos molestiae. Debitis consequuntur voluptate animi. Vel dolorem in et deserunt nihil. Odio deleniti voluptas vel excepturi tempora.', '1990-11-19', '2004-09-19', 9, 1);
INSERT INTO `mainapp_article` (`id`, `title`, `text`, `publish_date`, `updated_date`, `author`,`category`) VALUES (31, 'Est repellendus aut omnis officia autem aliquam dolores.', 'Quaerat fuga officiis ut. Non in magnam vel rerum. Sint sequi et aut rerum exercitationem.\nVoluptates enim eius rem cupiditate dolores. Quasi dicta officia atque.', '1988-01-10', '2000-04-16', 9, 1);
INSERT INTO `mainapp_article` (`id`, `title`, `text`, `publish_date`, `updated_date`, `author`,`category`) VALUES (32, 'Odit earum accusamus officiis exercitationem itaque et sed.', 'In non qui deserunt dolor ea et. Ut vel magni est dolores esse quam minima. Quis rerum tempore provident dicta. Autem quos soluta tempora hic autem sed aut eligendi.', '1972-03-23', '2000-09-16', 9, 1);
INSERT INTO `mainapp_article` (`id`, `title`, `text`, `publish_date`, `updated_date`, `author`,`category`) VALUES (33, 'Et fuga officiis unde doloremque dolorem voluptas aspernatur', 'Omnis aut quia fugit. Id ullam mollitia quasi expedita sit qui sed. Voluptatem dicta suscipit autem eaque voluptatem dolorem.', '2019-05-14', '2019-10-09', 5, 1);
INSERT INTO `mainapp_article` (`id`, `title`, `text`, `publish_date`, `updated_date`, `author`,`category`) VALUES (34, 'Molestiae sint necessitatibus explicabo earum ut maiores pos', 'Est dignissimos sit facere vitae cupiditate. Hic consequatur sunt fugiat ea et et qui quidem. Ut quae neque optio quis repellendus. Quas suscipit consequuntur blanditiis.', '1975-05-28', '1992-12-06', 0, 1);
INSERT INTO `mainapp_article` (`id`, `title`, `text`, `publish_date`, `updated_date`, `author`,`category`) VALUES (35, 'Optio porro ipsa aut ea consequatur nesciunt voluptatum volu', 'Earum debitis nisi architecto ea similique aut. Accusantium repudiandae sit harum nobis inventore. Qui quasi necessitatibus alias animi animi quis quia sed. Excepturi ut unde fuga voluptates.', '1974-07-09', '1979-06-25', 9, 1);
INSERT INTO `mainapp_article` (`id`, `title`, `text`, `publish_date`, `updated_date`, `author`,`category`) VALUES (36, 'Dolor culpa recusandae et beatae non.', 'Qui earum eos sequi vel molestiae. Recusandae quae rerum id sunt aut voluptatum iste accusamus. Sed aut dicta facere repellendus qui voluptatem quis. Amet ad dolor doloribus ab dolorum quidem.', '2008-09-15', '2022-02-09', 3, 1);
INSERT INTO `mainapp_article` (`id`, `title`, `text`, `publish_date`, `updated_date`, `author`,`category`) VALUES (37, 'Delectus dolorum voluptatem recusandae.', 'Enim voluptas aspernatur placeat. Et sed omnis corrupti eaque officia ex consectetur dolore. Cum dolore repellendus et explicabo corporis.', '1979-01-31', '2005-05-03', 9, 1);
INSERT INTO `mainapp_article` (`id`, `title`, `text`, `publish_date`, `updated_date`, `author`,`category`) VALUES (38, 'Accusamus molestiae autem neque est.', 'Et nobis vitae quod vel tenetur. Quis repudiandae natus provident aut reiciendis. Eaque ducimus inventore quos voluptatum.', '1974-10-18', '1982-12-04', 8, 1);
INSERT INTO `mainapp_article` (`id`, `title`, `text`, `publish_date`, `updated_date`, `author`,`category`) VALUES (39, 'Quia doloribus odio iusto illo voluptas eum.', 'In ut dolore natus architecto sunt voluptate consequuntur non. Sint sint iste quo quaerat repellendus illum eos. Ab asperiores distinctio iusto. Et illo labore nihil repellendus et.', '1970-10-28', '2014-02-18', 9, 1);
INSERT INTO `mainapp_article` (`id`, `title`, `text`, `publish_date`, `updated_date`, `author`,`category`) VALUES (40, 'Numquam laboriosam est est non et eos.', 'Necessitatibus debitis nulla facere aliquam at et. Quam fugit quia et. Odio ea et non recusandae optio repellat. Unde cum nisi laudantium vel accusantium ea eum.', '1986-05-24', '1972-02-10', 1, 1);
INSERT INTO `mainapp_article` (`id`, `title`, `text`, `publish_date`, `updated_date`, `author`,`category`) VALUES (41, 'Tempore natus consequuntur dolores quis occaecati.', 'A omnis velit aliquam in voluptatibus porro eos. Recusandae ab amet similique et veritatis. Omnis possimus blanditiis perferendis at ipsum molestiae porro consequuntur. Quam nemo excepturi earum.', '1984-06-27', '2009-07-18', 9, 1);
INSERT INTO `mainapp_article` (`id`, `title`, `text`, `publish_date`, `updated_date`, `author`,`category`) VALUES (42, 'Eaque ea voluptas qui.', 'Temporibus non aut provident nobis. Deserunt vitae nihil in nesciunt minima. Provident reiciendis nobis rem ut et ut.', '2008-09-27', '2012-12-30', 2, 1);
INSERT INTO `mainapp_article` (`id`, `title`, `text`, `publish_date`, `updated_date`, `author`,`category`) VALUES (43, 'Dolor qui quidem enim ut maxime quidem.', 'Est et nihil inventore sapiente velit. Quasi libero qui ad dolorem. Tempora dolorem natus doloribus quos ut ut voluptas.', '1976-08-13', '1982-06-23', 6, 1);
INSERT INTO `mainapp_article` (`id`, `title`, `text`, `publish_date`, `updated_date`, `author`,`category`) VALUES (44, 'Iusto quia alias consequatur esse debitis eaque.', 'Quo aut non et temporibus sed iusto rem. Doloremque doloremque cum et dolore hic aliquam. Aperiam delectus animi voluptas.', '1999-02-15', '2010-11-04', 2, 1);
INSERT INTO `mainapp_article` (`id`, `title`, `text`, `publish_date`, `updated_date`, `author`,`category`) VALUES (45, 'Vel veritatis optio ipsa non est officia.', 'Voluptatem aut placeat rerum voluptatibus eveniet est voluptatem. Distinctio sit vero eius quas a. Quo est nam suscipit cum. Ut et et repellat asperiores.', '1985-09-10', '1975-01-04', 2, 1);
INSERT INTO `mainapp_article` (`id`, `title`, `text`, `publish_date`, `updated_date`, `author`,`category`) VALUES (46, 'Necessitatibus sit eum nisi provident dolores vitae.', 'Error et doloremque corrupti temporibus amet molestias et. Quos unde qui qui ut consequuntur repudiandae ea. Veritatis minus fugit suscipit cum.', '2001-05-11', '2015-05-21', 6, 1);
INSERT INTO `mainapp_article` (`id`, `title`, `text`, `publish_date`, `updated_date`, `author`,`category`) VALUES (47, 'Hic eum quia in et excepturi quas illum.', 'Rerum voluptatem iure animi velit vel. Doloribus eveniet est deserunt ex rem cupiditate est deleniti. Deleniti nobis debitis labore qui illum doloremque corporis ut.', '1970-10-19', '2009-07-27', 8, 1);
INSERT INTO `mainapp_article` (`id`, `title`, `text`, `publish_date`, `updated_date`, `author`,`category`) VALUES (48, 'Voluptas animi sint eos nihil neque nesciunt dolores non.', 'Optio eius unde aliquid maxime et ut repudiandae. Et est nostrum delectus et. Recusandae voluptas alias laboriosam asperiores quis.', '1973-10-14', '1989-09-27', 4, 1);
INSERT INTO `mainapp_article` (`id`, `title`, `text`, `publish_date`, `updated_date`, `author`,`category`) VALUES (49, 'Sint corrupti omnis totam non rerum aut.', 'Hic id a reiciendis voluptatem nobis ex. Quia harum quo voluptatem exercitationem corporis et ut. Architecto expedita voluptatem alias autem laudantium temporibus omnis.', '1982-01-02', '2017-06-24', 1, 1);
INSERT INTO `mainapp_article` (`id`, `title`, `text`, `publish_date`, `updated_date`, `author`,`category`) VALUES (50, 'Vitae nam unde ullam expedita sint excepturi et.', 'Provident quod aut dolor ad ea. Dolor veritatis dolorem voluptatem officia. Et dolor expedita qui aliquid amet ad.', '1979-02-15', '2015-05-16', 1, 1);
INSERT INTO `mainapp_article` (`id`, `title`, `text`, `publish_date`, `updated_date`, `author`,`category`) VALUES (51, 'Consequuntur sint id illo minus hic enim.', 'Quia adipisci ut ut consequatur qui. Reprehenderit debitis officiis soluta rerum repellendus. Sapiente alias maiores ipsa quasi. Sunt aut nemo iure mollitia consequatur sunt ab.', '2017-08-19', '2003-05-14', 9, 1);
INSERT INTO `mainapp_article` (`id`, `title`, `text`, `publish_date`, `updated_date`, `author`,`category`) VALUES (52, 'Magnam dolores numquam laboriosam iure voluptatem.', 'Quasi eos vel fugit nihil. Quod aut at quia ducimus nostrum. Deleniti sed sapiente ut aperiam repellendus ipsa.', '2022-03-07', '1998-09-06', 7, 1);
INSERT INTO `mainapp_article` (`id`, `title`, `text`, `publish_date`, `updated_date`, `author`,`category`) VALUES (53, 'Quis similique amet consequuntur sit aut quaerat.', 'Eos et aut sequi fugiat. Commodi aut nesciunt repellendus voluptates odit cupiditate. Qui quos ea exercitationem corrupti soluta nulla.', '1991-09-18', '1980-10-04', 6, 1);
INSERT INTO `mainapp_article` (`id`, `title`, `text`, `publish_date`, `updated_date`, `author`,`category`) VALUES (54, 'Ipsam eaque est laudantium ut.', 'Sed consequatur ut ratione quaerat. Iure ipsa aut maiores et consequatur voluptatem. Optio sed sequi minima dolor harum labore quos.', '1981-01-14', '1975-12-21', 7, 1);
INSERT INTO `mainapp_article` (`id`, `title`, `text`, `publish_date`, `updated_date`, `author`,`category`) VALUES (55, 'Ea similique est maxime temporibus quis pariatur voluptatibu', 'Qui eveniet architecto pariatur. Aliquam optio amet unde est. Officiis ratione sed aut alias omnis quia ut. Porro rerum corporis enim iure non blanditiis sit.', '2015-02-15', '2005-02-07', 6, 1);
INSERT INTO `mainapp_article` (`id`, `title`, `text`, `publish_date`, `updated_date`, `author`,`category`) VALUES (56, 'Officiis qui ut consequatur expedita nulla.', 'Dolore aut doloribus alias est. Cum dolores libero nam magni aspernatur. Tenetur aperiam ut ut consequatur est qui.', '1988-06-05', '1986-11-19', 8, 1);
INSERT INTO `mainapp_article` (`id`, `title`, `text`, `publish_date`, `updated_date`, `author`,`category`) VALUES (57, 'Est dolorem et et quia.', 'Molestiae velit cum porro ducimus est et at. Adipisci hic id in et. Facere dolores ea officia deserunt voluptate et recusandae.', '1971-05-08', '1992-03-09', 6, 1);
INSERT INTO `mainapp_article` (`id`, `title`, `text`, `publish_date`, `updated_date`, `author`,`category`) VALUES (58, 'Non ipsum rerum nulla in autem recusandae.', 'Libero eveniet dolorum tenetur nihil ut. Omnis a perspiciatis laborum veritatis occaecati quasi. Fugit quidem provident et omnis dicta sit.', '1970-07-23', '1996-05-26', 7, 1);
INSERT INTO `mainapp_article` (`id`, `title`, `text`, `publish_date`, `updated_date`, `author`,`category`) VALUES (59, 'Voluptatibus dolorum debitis eaque soluta totam non voluptas', 'Qui ea non est rerum explicabo omnis. Hic explicabo est qui quia tempore nobis doloribus. Iste repudiandae dolorem fuga assumenda molestias itaque.', '1991-09-15', '2021-02-21', 9, 1);
INSERT INTO `mainapp_article` (`id`, `title`, `text`, `publish_date`, `updated_date`, `author`,`category`) VALUES (60, 'Exercitationem qui quam sint et.', 'Corporis perspiciatis sint velit omnis. Repudiandae voluptas eos officia. Atque nesciunt dolorem praesentium aspernatur sint illum doloribus corrupti. Repellat dolores illo deserunt est facere.', '2003-10-22', '1999-06-19', 2, 1);
INSERT INTO `mainapp_article` (`id`, `title`, `text`, `publish_date`, `updated_date`, `author`,`category`) VALUES (61, 'Aliquid porro non non voluptatum in aperiam.', 'Voluptatem similique unde ut ut sit deleniti. Deserunt exercitationem accusantium consequuntur alias sit voluptatibus sed inventore. Nulla et quia nam sapiente est.', '2002-10-07', '2016-08-03', 4, 1);
INSERT INTO `mainapp_article` (`id`, `title`, `text`, `publish_date`, `updated_date`, `author`,`category`) VALUES (62, 'Delectus porro incidunt quasi sint.', 'Magni ut voluptate quia quo cupiditate enim fugit. Reprehenderit eos autem quo laudantium eveniet. Excepturi dolorem voluptatibus illum.', '1991-07-05', '2014-04-23', 1, 1);
INSERT INTO `mainapp_article` (`id`, `title`, `text`, `publish_date`, `updated_date`, `author`,`category`) VALUES (63, 'Occaecati enim molestiae amet et suscipit dolor.', 'Doloremque aut assumenda est tempore delectus. Facere recusandae quibusdam voluptas animi voluptatem. Quibusdam libero illo ut voluptate saepe saepe.', '1994-03-26', '1970-08-11', 0, 1);
INSERT INTO `mainapp_article` (`id`, `title`, `text`, `publish_date`, `updated_date`, `author`,`category`) VALUES (64, 'Vitae aut debitis et.', 'Iusto vel autem consectetur aut. Dolor magni at accusantium. Voluptatibus minus soluta aut dolor.', '1993-05-11', '1992-05-01', 1, 1);
INSERT INTO `mainapp_article` (`id`, `title`, `text`, `publish_date`, `updated_date`, `author`,`category`) VALUES (65, 'Rerum est eum sit repellat sunt quis.', 'Similique magni voluptate quo sint possimus excepturi totam. Quia praesentium inventore nobis sit dolores.', '1970-05-24', '2015-09-03', 7, 1);
INSERT INTO `mainapp_article` (`id`, `title`, `text`, `publish_date`, `updated_date`, `author`,`category`) VALUES (66, 'Blanditiis quia est pariatur aut laborum reiciendis voluptat', 'Culpa molestiae et reiciendis illum. Voluptates voluptatem vel exercitationem officiis nihil numquam quia. Et quia eaque deserunt sunt.', '2009-06-02', '2009-07-25', 8, 1);
INSERT INTO `mainapp_article` (`id`, `title`, `text`, `publish_date`, `updated_date`, `author`,`category`) VALUES (67, 'Repellendus deleniti architecto fuga libero accusantium sit.', 'Non vero ut aut qui sed. Aut deserunt corrupti labore laborum rem non. Qui et asperiores vel totam. Vero facilis ea dolor vero est.', '1994-04-01', '2015-08-06', 6, 1);
INSERT INTO `mainapp_article` (`id`, `title`, `text`, `publish_date`, `updated_date`, `author`,`category`) VALUES (68, 'Eum et officia eligendi est.', 'Commodi omnis molestiae tempora ut aut maiores. Possimus voluptate maiores eos sint voluptates. Sit nisi et et molestiae consectetur dolores eaque consequatur. Quas soluta eveniet excepturi dolor.', '1999-07-26', '2003-06-24', 7, 1);
INSERT INTO `mainapp_article` (`id`, `title`, `text`, `publish_date`, `updated_date`, `author`,`category`) VALUES (69, 'Quaerat ut et occaecati.', 'Dignissimos minima quas assumenda aliquid. Quas expedita quia fugiat earum. Dolores quia accusantium numquam. Temporibus molestias quidem commodi quia.', '2001-01-21', '2009-12-01', 8, 1);
INSERT INTO `mainapp_article` (`id`, `title`, `text`, `publish_date`, `updated_date`, `author`,`category`) VALUES (70, 'Magni nostrum omnis aut omnis.', 'Placeat quia ullam officiis dolorem nisi. Impedit dolores rerum vero officia. Et molestiae fugit aut reprehenderit non sit suscipit.', '1972-07-14', '1985-05-14', 1, 1);
INSERT INTO `mainapp_article` (`id`, `title`, `text`, `publish_date`, `updated_date`, `author`,`category`) VALUES (71, 'Quibusdam accusantium corporis qui deleniti est est voluptat', 'Ut qui beatae aliquam autem ratione eius. Ratione minus totam explicabo quia eius nostrum. Dolores neque quam voluptas eius architecto. Autem dolores beatae amet facilis.', '2020-05-22', '2008-02-16', 3, 1);
INSERT INTO `mainapp_article` (`id`, `title`, `text`, `publish_date`, `updated_date`, `author`,`category`) VALUES (72, 'Optio unde recusandae iste est dicta.', 'Veniam omnis odio quos omnis ut. Consequuntur et fugiat eius quis eos. Sed voluptas alias optio rem maxime excepturi deserunt.', '2009-09-03', '2014-06-25', 6, 1);
INSERT INTO `mainapp_article` (`id`, `title`, `text`, `publish_date`, `updated_date`, `author`,`category`) VALUES (73, 'Et omnis adipisci molestiae voluptatem unde sunt.', 'Neque nihil sed et corporis reiciendis iure corporis consequatur. Accusamus dolor architecto itaque rerum. Autem sed tempore minima expedita asperiores illo sunt.', '1989-01-07', '1984-01-30', 3, 1);
INSERT INTO `mainapp_article` (`id`, `title`, `text`, `publish_date`, `updated_date`, `author`,`category`) VALUES (74, 'Tenetur rem voluptates doloremque id rerum.', 'Qui quia rerum similique quaerat fugit. Est libero voluptatibus molestias. Possimus fugit consectetur eligendi aliquam similique laudantium illo tenetur. Ea delectus consequatur ipsam.', '2013-05-12', '2005-09-21', 5, 1);
INSERT INTO `mainapp_article` (`id`, `title`, `text`, `publish_date`, `updated_date`, `author`,`category`) VALUES (75, 'Tempore et nam soluta corporis.', 'Odit consequuntur consequuntur cumque. Fugit possimus enim quos recusandae officiis quod. Debitis nihil enim ipsum. Rerum error placeat vel exercitationem nemo in architecto explicabo.', '2015-07-30', '1978-09-29', 2, 1);
INSERT INTO `mainapp_article` (`id`, `title`, `text`, `publish_date`, `updated_date`, `author`,`category`) VALUES (76, 'Ut laborum dignissimos voluptatem repellendus explicabo mole', 'Quia facere esse quisquam. Pariatur voluptatum nemo animi architecto sed. Dolorum vel vitae ipsum aut. Vel omnis laboriosam cumque et quis reiciendis doloremque.', '2011-09-23', '1988-07-26', 5, 1);
INSERT INTO `mainapp_article` (`id`, `title`, `text`, `publish_date`, `updated_date`, `author`,`category`) VALUES (77, 'Culpa nihil id doloribus sed velit facilis.', 'Distinctio neque eaque voluptatibus architecto vero esse. Cumque cumque consequuntur vero nam aut voluptatem. Ex dolorem temporibus aut illo minus consequatur. Aliquam aliquid consectetur nobis.', '1977-08-26', '2008-10-02', 4, 1);
INSERT INTO `mainapp_article` (`id`, `title`, `text`, `publish_date`, `updated_date`, `author`,`category`) VALUES (78, 'Sunt et aut dolore quaerat.', 'Et in ad tempore recusandae voluptates voluptate. Deserunt optio quo dolorem dicta doloremque. Asperiores beatae ex ullam atque architecto quibusdam sit.', '1991-11-21', '1986-12-29', 4, 1);
INSERT INTO `mainapp_article` (`id`, `title`, `text`, `publish_date`, `updated_date`, `author`,`category`) VALUES (79, 'Quos nihil maiores laboriosam inventore ex ut.', 'Omnis voluptates ut alias velit. Facere beatae dolor distinctio consequatur esse libero excepturi et. Sit aut quia repellendus. Non consequuntur ut fugit earum accusamus unde.', '1991-05-28', '1976-11-25', 8, 1);
INSERT INTO `mainapp_article` (`id`, `title`, `text`, `publish_date`, `updated_date`, `author`,`category`) VALUES (80, 'Et velit blanditiis voluptatibus dolores.', 'Magni voluptas omnis tempora alias nesciunt debitis aut. Porro et quasi possimus perspiciatis fugit. Enim sit dolorum reprehenderit quo sed. Quod delectus illum ut consectetur voluptate ut.', '2010-02-26', '2016-06-25', 7, 1);
INSERT INTO `mainapp_article` (`id`, `title`, `text`, `publish_date`, `updated_date`, `author`,`category`) VALUES (81, 'Facilis eos ut aliquam voluptas ut qui sint veritatis.', 'Animi non incidunt suscipit illo ratione. Ut suscipit non ut sed laborum. Sequi itaque vel quod consequatur.', '2000-01-31', '1979-12-13', 1, 1);
INSERT INTO `mainapp_article` (`id`, `title`, `text`, `publish_date`, `updated_date`, `author`,`category`) VALUES (82, 'Eligendi qui ullam rerum commodi.', 'Quo aspernatur architecto incidunt fugiat. Ad deserunt unde eaque voluptas tenetur illum voluptatem. Aut cum necessitatibus velit. Ut quis inventore atque quidem omnis.', '2007-12-19', '1974-09-07', 1, 1);
INSERT INTO `mainapp_article` (`id`, `title`, `text`, `publish_date`, `updated_date`, `author`,`category`) VALUES (83, 'Molestiae reprehenderit ea magnam iusto.', 'Rerum ut reiciendis in sint sit sequi qui et. Tempora quia qui voluptatibus dolorem quibusdam sint vel laboriosam. Non blanditiis omnis ea dolorem in fugit neque.', '2014-04-01', '1973-12-07', 4, 1);
INSERT INTO `mainapp_article` (`id`, `title`, `text`, `publish_date`, `updated_date`, `author`,`category`) VALUES (84, 'Vero in assumenda nihil est quis molestiae odit.', 'Fugit nam et vel earum quas et repudiandae. Quia corrupti officia enim velit eligendi. Dolor molestiae aliquid doloribus voluptate porro. Similique vero et optio dolor.', '1979-10-08', '2010-06-11', 3, 1);
INSERT INTO `mainapp_article` (`id`, `title`, `text`, `publish_date`, `updated_date`, `author`,`category`) VALUES (85, 'Fugit voluptas consequuntur animi error aut sed illo.', 'Laborum sit ut voluptas quod ab sapiente. Consequatur ducimus illum omnis et. Id et veniam molestiae fuga maiores impedit saepe. Facere delectus libero iure consequatur qui excepturi.', '1984-07-13', '2011-04-06', 8, 1);
INSERT INTO `mainapp_article` (`id`, `title`, `text`, `publish_date`, `updated_date`, `author`,`category`) VALUES (86, 'Assumenda sapiente nobis aperiam quaerat ab repellat.', 'Quibusdam ab delectus eaque aliquid nam ex. Aliquid vel voluptate et et beatae vero. Ea neque nobis magni quam. Ducimus ratione cumque delectus voluptatum quo.', '2019-07-20', '2014-07-24', 2, 1);
INSERT INTO `mainapp_article` (`id`, `title`, `text`, `publish_date`, `updated_date`, `author`,`category`) VALUES (87, 'Beatae asperiores porro in explicabo.', 'Temporibus exercitationem atque quasi enim consequatur saepe nam. Iste dicta consequuntur amet in et. Quia rerum velit ut.', '2020-11-19', '2021-06-07', 8, 1);
INSERT INTO `mainapp_article` (`id`, `title`, `text`, `publish_date`, `updated_date`, `author`,`category`) VALUES (88, 'Quam tempora aliquam est eius.', 'Ullam quia velit accusantium maiores consequatur numquam. Et distinctio qui distinctio ea adipisci. Aut odio repudiandae atque doloremque ipsum et provident.', '1988-11-11', '2002-07-28', 9, 1);
INSERT INTO `mainapp_article` (`id`, `title`, `text`, `publish_date`, `updated_date`, `author`,`category`) VALUES (89, 'Quod veniam at nesciunt.', 'Ex enim veniam soluta tempora et officia exercitationem. Deserunt quod unde laborum quis. Placeat suscipit autem aliquid. Eum dolor minus molestiae.', '2005-03-05', '1998-12-11', 7, 1);
INSERT INTO `mainapp_article` (`id`, `title`, `text`, `publish_date`, `updated_date`, `author`,`category`) VALUES (90, 'Voluptate alias ut delectus amet quo.', 'Eum quis quos ut fuga. Eligendi qui enim dolores hic. Magni dolore voluptatem voluptas quos sed qui laboriosam. Omnis ut ducimus nobis autem autem aut velit labore.', '1981-01-15', '1998-07-02', 5, 1);
INSERT INTO `mainapp_article` (`id`, `title`, `text`, `publish_date`, `updated_date`, `author`,`category`) VALUES (91, 'Error est cum voluptatem neque sed repellendus.', 'Et odio ut ab expedita aspernatur. Similique eos harum magni non rerum magni. Officia quas blanditiis laborum molestiae et aperiam exercitationem. Magni odit cumque aut incidunt.', '2011-01-05', '1977-04-23', 3, 1);
INSERT INTO `mainapp_article` (`id`, `title`, `text`, `publish_date`, `updated_date`, `author`,`category`) VALUES (92, 'Ut recusandae occaecati quae quos est.', 'Totam aliquam ut dolorem itaque a temporibus molestiae. Consequatur autem amet id eum commodi. Laboriosam voluptate ut et cumque voluptas. Perspiciatis dignissimos itaque vel incidunt sunt quae.', '2021-03-12', '1999-04-10', 2, 1);
INSERT INTO `mainapp_article` (`id`, `title`, `text`, `publish_date`, `updated_date`, `author`,`category`) VALUES (93, 'Earum totam qui impedit non at.', 'Fuga voluptas rerum explicabo mollitia tenetur autem. Eum quia qui nostrum voluptatum. Inventore harum reiciendis dolor velit.', '1973-06-04', '2007-01-06', 9, 1);
INSERT INTO `mainapp_article` (`id`, `title`, `text`, `publish_date`, `updated_date`, `author`,`category`) VALUES (94, 'Sed quas quia occaecati modi autem.', 'Voluptate aliquam odio repudiandae deleniti sit voluptatem optio eaque. Eum assumenda assumenda quidem omnis. Aut ullam debitis ea aliquid.', '1995-03-18', '2003-04-17', 8, 1);
INSERT INTO `mainapp_article` (`id`, `title`, `text`, `publish_date`, `updated_date`, `author`,`category`) VALUES (95, 'Unde id esse tenetur porro aliquam.', 'Veniam illum qui est esse a ut recusandae. Dolorem deserunt ut perspiciatis et. Eius repellendus ea vero rerum. Doloribus voluptates placeat suscipit quas veniam alias excepturi.', '1996-09-15', '2009-01-23', 0, 1);
INSERT INTO `mainapp_article` (`id`, `title`, `text`, `publish_date`, `updated_date`, `author`,`category`) VALUES (96, 'Mollitia ducimus provident deserunt facilis voluptas et.', 'Nobis nesciunt et occaecati aut in et. Voluptatem sit dolores tempore et modi. Odit fugit sed sed ut occaecati esse omnis et.', '1989-09-20', '2015-05-08', 3, 1);
INSERT INTO `mainapp_article` (`id`, `title`, `text`, `publish_date`, `updated_date`, `author`,`category`) VALUES (97, 'Sit perferendis dolores quod harum.', 'Minima sit consequatur quisquam aut. Voluptatem quasi eius non. Dolorum labore tempore esse sit nulla excepturi aut ipsum.', '2006-02-14', '1987-12-13', 3, 1);
INSERT INTO `mainapp_article` (`id`, `title`, `text`, `publish_date`, `updated_date`, `author`,`category`) VALUES (98, 'Eaque eum nostrum numquam voluptatem voluptates.', 'Eum ipsum omnis quia animi exercitationem nam quo porro. Sapiente odio exercitationem explicabo quos unde ducimus fugit cupiditate. At est ducimus et. Praesentium in facilis sit saepe.', '1987-05-15', '2020-02-16', 0, 1);
INSERT INTO `mainapp_article` (`id`, `title`, `text`, `publish_date`, `updated_date`, `author`,`category`) VALUES (99, 'Id autem et sapiente fugiat veritatis recusandae.', 'Quia asperiores ad nihil quia in. Cumque nihil dicta aut dolore. Atque est officiis corporis eius. Et rerum labore et quaerat sunt.', '1990-05-29', '2002-02-22', 7, 1);
INSERT INTO `mainapp_article` (`id`, `title`, `text`, `publish_date`, `updated_date`, `author`,`category`) VALUES (100, 'Soluta esse repudiandae praesentium voluptatem.', 'Natus qui veritatis dolores ratione quasi vel iure. Quas suscipit aut error assumenda in voluptate. Quia velit nihil quo adipisci et at ut.', '2011-05-21', '1972-09-22', 7, 1);


