# Generated by Django 4.0.3 on 2022-04-18 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_article_publish_date_and_more'),
        ('mainapp', '0002_alter_article_title'),
    ]

    operations = [
    ]
