# Generated by Django 4.0.3 on 2022-04-19 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_article_publish_date_alter_article_title_and_more'),
        ('mainapp', '0003_merge_20220418_1755'),
    ]

    operations = [
    ]
