# Generated by Django 4.0.3 on 2022-04-20 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'комментарий', 'verbose_name_plural': 'комментарии'},
        ),
    ]
