# Generated by Django 4.0.3 on 2022-05-02 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_comment_is_visible'),
        ('mainapp', '0010_comment_moderation_required'),
    ]

    operations = [
    ]
