# Generated by Django 4.0.3 on 2022-05-04 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_merge_20220502_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_visible',
            field=models.BooleanField(default=False),
        ),
    ]
