# Generated by Django 4.0.3 on 2022-05-06 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
