# Generated by Django 4.0.3 on 2022-05-09 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_article_is_visible'),
        ('mainapp', '0014_notification_url'),
    ]

    operations = [
    ]
