# Generated by Django 4.0.3 on 2022-05-09 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_merge_0012_article_is_visible_0014_notification_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='childs', to='mainapp.comment'),
        ),
        migrations.AlterField(
            model_name='article',
            name='is_visible',
            field=models.BooleanField(default=False, verbose_name='Опубликовано'),
        ),
        migrations.AlterField(
            model_name='article',
            name='moderation_required',
            field=models.BooleanField(default=True, verbose_name='Требуется модерация'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.TextField(verbose_name='Текст комментария'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='is_visible',
            field=models.BooleanField(default=True, verbose_name='Опубликовано'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='moderation_required',
            field=models.BooleanField(default=True, verbose_name='Требуется модерация'),
        ),
    ]
