# Generated by Django 4.0.3 on 2022-05-19 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0018_article_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='pic',
            field=models.ImageField(blank=True, upload_to='article_pics/', verbose_name='обложка статьи'),
        ),
        migrations.AddField(
            model_name='article',
            name='preview_text',
            field=models.TextField(blank=True, verbose_name='превью'),
        ),
        migrations.AddField(
            model_name='article',
            name='source_text',
            field=models.CharField(blank=True, max_length=250, verbose_name='текст источника'),
        ),
        migrations.AddField(
            model_name='article',
            name='source_url',
            field=models.CharField(blank=True, max_length=250, verbose_name='ссылка на источник'),
        ),
    ]
