# Generated by Django 4.0.3 on 2022-05-21 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0018_alter_comment_moderation_required'),
        ('mainapp', '0018_article_views'),
    ]

    operations = [
    ]
