# Generated by Django 4.0.3 on 2022-05-24 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0019_article_pic_article_preview_text_article_source_text_and_more'),
        ('mainapp', '0019_merge_20220521_1510'),
    ]

    operations = [
    ]
