# Generated by Django 4.0.3 on 2022-05-28 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0020_merge_20220523_1012'),
        ('mainapp', '0020_merge_20220524_2008'),
    ]

    operations = [
    ]
