# Generated by Django 4.0.3 on 2022-05-30 08:14

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0021_merge_20220528_1221'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_us', tinymce.models.HTMLField(blank=True, verbose_name='о нас')),
                ('logo_pic', models.ImageField(blank=True, default='site_pics/default_logo.png', upload_to='site_pics/', verbose_name='лого сайта')),
            ],
            options={
                'verbose_name': 'настройки сайта',
                'verbose_name_plural': 'настройки сайта',
            },
        ),
    ]
