# Generated by Django 4.0.3 on 2022-06-04 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0023_merge_0020_merge_20220529_1841_0022_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='pinned_article',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pinned_article', to='mainapp.article'),
        ),
    ]
