# Generated by Django 4.0.3 on 2022-04-20 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kbankuser',
            name='avatar',
            field=models.ImageField(blank=True, default='/users_avatar/default.png', upload_to='users_avatar/'),
        ),
    ]
