# Generated by Django 4.0.3 on 2022-04-20 20:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_alter_kbankuser_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='kbankuser',
            name='activation_key',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='kbankuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 21, 20, 29, 36, 546461, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='kbankuser',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
