# Generated by Django 4.0.3 on 2022-04-23 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_alter_kbankuser_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='kbankuser',
            name='is_moderator',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='kbankuser',
            name='avatar',
            field=models.ImageField(blank=True, default='/users_avatar/default.png', upload_to='users_avatar/', verbose_name='аватар'),
        ),
    ]
