# Generated by Django 4.0.3 on 2022-04-21 19:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_kbankuser_activation_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kbankuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 22, 19, 45, 52, 451683, tzinfo=utc)),
        ),
    ]
