# Generated by Django 4.0.3 on 2022-04-22 20:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_alter_kbankuser_activation_key_expires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kbankuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 23, 20, 53, 41, 235909, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='kbankuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True, verbose_name=('email address',)),
        ),
    ]
