# Generated by Django 4.0.3 on 2022-04-24 16:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0007_alter_kbankuser_activation_key_expires_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kbankuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 25, 16, 2, 36, 558847, tzinfo=utc)),
        ),
    ]
