# Generated by Django 4.0.3 on 2022-04-25 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0006_merge_20220424_2254'),
        ('authapp', '0008_alter_kbankuser_activation_key_expires'),
    ]

    operations = [
    ]
