# Generated by Django 4.0.3 on 2022-04-27 15:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0008_alter_kbankuser_activation_key_expires'),
    ]

    operations = [
        migrations.AddField(
            model_name='kbankuser',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='kbankuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 28, 15, 46, 42, 819963, tzinfo=utc)),
        ),
    ]
