# Generated by Django 4.0.3 on 2022-04-27 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0009_kbankuser_is_blocked_and_more'),
        ('authapp', '0010_alter_kbankuser_activation_key_expires'),
    ]

    operations = [
    ]
