# Generated by Django 4.0.3 on 2022-04-28 15:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0010_alter_kbankuser_activation_key_expires'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kbankuser',
            name='is_blocked',
        ),
        migrations.AlterField(
            model_name='kbankuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 29, 15, 57, 18, 24457, tzinfo=utc)),
        ),
    ]
