# Generated by Django 4.0.3 on 2022-04-28 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0011_merge_20220427_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='kbankuser',
            name='moderation_required',
            field=models.BooleanField(default=True),
        ),
    ]
