# Generated by Django 4.0.3 on 2022-05-02 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0009_merge_20220425_2032'),
        ('authapp', '0012_kbankuser_is_blocked_and_more'),
        ('authapp', '0012_kbankuser_moderation_required'),
    ]

    operations = [
    ]
