# Generated by Django 4.0.3 on 2022-06-09 17:01

import authapp.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0015_alter_kbankuser_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kbankuser',
            options={'verbose_name': 'пользователь', 'verbose_name_plural': 'пользователи'},
        ),
        migrations.AlterField(
            model_name='kbankuser',
            name='activation_key',
            field=models.CharField(blank=True, max_length=128, verbose_name='ключ активации'),
        ),
        migrations.AlterField(
            model_name='kbankuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=authapp.models.default_key_expires, verbose_name='срок действия ключа активации'),
        ),
        migrations.AlterField(
            model_name='kbankuser',
            name='block_expires',
            field=models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0), verbose_name='время окончания блокировки'),
        ),
        migrations.AlterField(
            model_name='kbankuser',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='активен'),
        ),
        migrations.AlterField(
            model_name='kbankuser',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='удалено'),
        ),
        migrations.AlterField(
            model_name='kbankuser',
            name='is_moderator',
            field=models.BooleanField(default=False, verbose_name='модератор'),
        ),
    ]
